version: '3.7'

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  mysql_data1:
    name: mysql_data1

services:

  mydata:
    image: mysql:8.0
    container_name: mydata
    networks:
      - my-network
    restart: always
    volumes:
      - mysql_data1:/var/lib/mysql
    ports:
      - 4704:3306
      - 47040:33060
    env_file:
      - ./environment.env
    environment:
      - MYSQL_ROOT_HOST=%



